# Generated by Django 6.1.1 on 2026-10-06 13:23

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
